#!/usr/bin/env bash

#********************************
# Author: luis Sagastume
# Email: lsagastume1990@gmail.com
# File:  install
# Install dotfiles
#********************************

#Dotfiles
dotfiles=".vimrc .zshrc .bashrc .tmux.conf .pryrc .gemrc .gitconfig"

#*********************
# Valid args function
# Check valid dotfile
#*********************
function valid_arg()
{
    valid=1
    arg="$1"

    for file in $dotfiles; do
        if [ "$file" == "$arg" ]; then
            valid=0
            break
        fi
    done
    echo $valid
}

#************************************************
# vimrc setup function
# will configure vimrc and init.vim
#************************************************
function vimrc_setup()
{
    # Need curl to install vim-plug
    dependency=curl
    git_message=$(type $dependency)
    if  echo $git_message | grep --invert-match -iq "not found"; then
        echo "Setting up vim-plug"
    else
        echo "Can't complete vim/nvim configuration, install $dependency to continue"
        exit 1
    fi

    [ "$XDG_CONFIG_HOME" == "" ] && XDG_CONFIG_HOME="$HOME/.config"

    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    curl -fLo $XDG_CONFIG_HOME/nvim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

    if [ "$#" -gt 0 ] && [ "$1" == "y" ]; then
        if [ -h "$XDG_CONFIG_HOME/nvim/init.vim" ]; then
            unlink "$XDG_CONFIG_HOME/nvim/init.vim"
        fi
    fi

    ln -s ~/.vimrc "$XDG_CONFIG_HOME/nvim/init.vim"
}

# Create directory to backup files
[ ! -d "$PWD/backups" ] && mkdir "$PWD/backups"

#************************************************
# Setup function
# will handle configuration and update of dotfiles
#************************************************
function setup()
{
    file="$1"

    # Check input
    is_valid=$(valid_arg "$file")
    if [ $is_valid -eq 1 ]; then
        echo "ERROR: Invalid dotfile \"$file\""
        help
    fi

    if [ ! -e ~/"$file" ]; then
        echo "Setting up $file"

        ln -s "$PWD/${file#.}" ~/"$file" # ${string#substring} remove substring from string
        [ "$file" == ".vimrc" ] && vimrc_setup
    else
        echo -n "$file file already exists, do you want to update it [y/n]: "
        read update
        if [ "$update" == "y" ]; then
            old_file="${file#.}-$(date +%m-%d-%Y:%c)"
            touch "$PWD/backups/$old_file"
            cp ~/"$file" "$PWD/backups/$old_file"; unlink ~/"$file"
            ln -s "$PWD/${file#.}" ~/"$file"
            [ "$file" == ".vimrc" ] && vimrc_setup $update

            echo "$file updated"
        fi
    fi
}

#**********************************
# Clean function
# Remove everything from backup dir
#**********************************
function clean()
{
    rm "$PWD/backups/*"
}

#****************************************
# Help function
# Display available args to setup program
#****************************************
function help()
{
    i=1
    echo "Setup a specific file choosing one of the following arguments:"
    for file in $dotfiles; do
        echo "($i) $file"
        i=$((i+1))
    done
    exit 0
}

# Get input
arg=$1

# Run the setup
if [ $# -gt 0 ]; then
    if [ "$arg" == "--help" ]; then
        help
    elif [ "$arg" == "--clean" ]; then
        clean
    else
        setup $arg
    fi
else
    for file in $dotfiles; do
        setup $file
    done
fi
